Document: libktomgirl
Title: Debian libktomgirl Manual
Author: <insert document author here>
Abstract: This manual describes what libktomgirl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libktomgirl/libktomgirl.sgml.gz

Format: postscript
Files: /usr/share/doc/libktomgirl/libktomgirl.ps.gz

Format: text
Files: /usr/share/doc/libktomgirl/libktomgirl.text.gz

Format: HTML
Index: /usr/share/doc/libktomgirl/html/index.html
Files: /usr/share/doc/libktomgirl/html/*.html
